### PR TITLE
Fix German "E-Mail" spelling, minor improvement

### PR DESCRIPTION
**Pull request by danleh**
... of newlines in registration email.

### CODE REVIEW

**Comment by Clemens85** [comment]
Thanks for the enhancement. To be honest I never cared about the spelling, there are several valid ways, both E-Mail and Email is valid as far as I know.
Having said that, I can also just merge this, because E-Mail is just as good for me. 
But, there are also other translation bundles in the webclient (far more than in the backend, refer to runningdinner-client/shared/src/i18n/translations), and those should then also be adapted to have a consistent spelling.

**Comment by danleh** [comment]
Ah, good point, I changed the German spelling in the other translation bundles (and a few Java files that didn't use i18n) as well now.

**Comment by Clemens85** [comment]
Sorry, I still found at least one translation with the old style (e.g. "EMail für Rückfragen (wird in Event angezeigt" -> CommonMessages_lang_de.json)

**Comment by danleh** [comment]
Oops, thanks. I had only looked for "Email", now I also changed "EMail" in the German translations.

**Review by Clemens85 — APPROVED** [review]
Sry needed some time to finally check the PR, but is now merged and I will soon deploy it live

**Pull request merged**
